name: CI

on:
  push:
    branches:
      - master
    tags:
      - v*
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build with JDK ${{ matrix.jdk }}
    strategy:
      matrix:
        jdk: [1.8, 11, 13]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Cache Maven Repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-repository-${{ runner.os }}
          restore-keys: |
            maven-repository-

      - name: Set up JDK ${{ matrix.jdk }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.jdk }}

      - name: Build and run Tests
        run: mvn -B clean verify

  release:
    name: Release
    needs: build
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - name: Set Release Version
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})

      - uses: actions/checkout@v2

      - name: Cache Maven Repository
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: maven-repository-${{ runner.os }}
          restore-keys: |
            maven-repository-

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Deploy to Bintray
        env:
          MAVEN_DEPLOYMENT_USERNAME: ${{ secrets.MAVEN_DEPLOYMENT_USERNAME }}
          MAVEN_DEPLOYMENT_PASSWORD: ${{ secrets.MAVEN_DEPLOYMENT_PASSWORD }}
        run: mvn -B -Drevision="${{ env.RELEASE_VERSION }}" clean deploy -P release --settings ./settings.xml

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Version ${{ env.RELEASE_VERSION }}
          draft: false
          prerelease: false

      - name: Sync to Maven Central
        env:
          BINTRAY_USERNAME: ${{ secrets.MAVEN_DEPLOYMENT_USERNAME }}
          BINTRAY_PASSWORD: ${{ secrets.MAVEN_DEPLOYMENT_PASSWORD }}
          BINTRAY_REPO_NAME: "maven"
          BINTRAY_PACKAGE_NAME: "maven-parent"
          BINTRAY_VERSION: ${{ env.RELEASE_VERSION }}
        run: |
          curl -s -S -u "${{ secrets.BINTRAY_USERNAME }}:${{ secrets.BINTRAY_PASSWORD }}"
          -X POST --header "Content-Type: application/json" --data '{"close":"1"}'
          "https://api.bintray.com/maven_central_sync/${{ secrets.BINTRAY_USERNAME }}/${{ env.BINTRAY_REPO_NAME }}/${{ env.BINTRAY_PACKAGE_NAME }}/versions/${{ env.BINTRAY_VERSION }}"
